name: Build

on:
  push:
    # run on branch pushes...
    branches: [ main ]
    # ...and on tag pushes matching v*
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y libpoppler-glib-dev poppler-utils libwxgtk3.2-dev

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Build source tarball
        run: make dist

      - name: Package Linux binary
        run: |
          mkdir linux-dist
          cp diff-pdf linux-dist/
          cp README* LICENSE* linux-dist/ 2>/dev/null || true
          tar -czvf diff-pdf-linux.tar.gz -C linux-dist .

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: diff-pdf-linux.tar.gz

      - name: Upload source tarball
        uses: actions/upload-artifact@v4
        with:
          name: source-tarball
          path: diff-pdf-*.tar.gz

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc automake autoconf pkg-config make zip
            mingw-w64-ucrt-x86_64-poppler
            mingw-w64-ucrt-x86_64-wxwidgets3.2-common
            mingw-w64-ucrt-x86_64-wxwidgets3.2-msw
            mingw-w64-ucrt-x86_64-wxwidgets3.2-msw-libs

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Build Windows archive
        run: make windows-dist

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: win-binaries
          path: diff-pdf*.zip

  publish-release:
    name: Publish release
    needs: [ build-linux, build-windows ]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: linux-binaries
          path: artifacts/linux

      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: win-binaries
          path: artifacts/windows

      - name: Download source tarball
        uses: actions/download-artifact@v4
        with:
          name: source-tarball
          path: artifacts/source

      - name: Flatten artifacts to workspace root
        run: |
          cp artifacts/linux/* .
          cp artifacts/windows/* .
          cp artifacts/source/* .

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          # explicit tag to use
          tag: ${{ github.ref_name }}
          # human-friendly release name
          name: Release ${{ github.ref_name }}
          # combine both tars and zips
          artifacts: "*.tar.gz,*.zip"
          # allow updating an existing prerelease if re-run
          allowUpdates: true
          # change to `false` if you want a full, non-prerelease release
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
